### ISSUE TITLE
Refactor set_viewpoint method

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/blacklight-maps#65]
When updating tests, this method appears to be doing just too much. Perhaps this should be a class itself?

**Comment by mejackreed** [comment]
@ebenenglish Can you confirm what the expected return values are for `set_viewpoint`? Also is the anticipated behavior to return something to set the map location in the UI?

**Comment by ebenenglish** [comment]
@mejackreed ```set_viewpoint``` is used to set the Leaflet map bounds in the UI when there are a diverse set of locations being passed to the map. The function loops through all the coordinates in the GeoJSON featureCollection and returns a bounding box or coordinate set that is passed to the Leafleft ```fitBounds``` method, which determines the correct center point and zoom level. The result it that all the locations are visible in the map window in the UI (with a little bit of padding), and the zoom is as deep as possible where all the locations can still be seen on the initial load.

`set_viewpoint` should either return (a) an array with one coordinate point; or (b) an array with two members, where each member is a coordinate point array :
```
point => [29.646923, 91.117212]
bbox => [[20.593684, 78.96288], [35.86166, 104.195397]]
```
It could probably be broken down into several smaller functions or moved into a class.

**Comment by mejackreed** [comment]
Thanks for the great reply. I'm working on it
