### ISSUE TITLE
map doesn't zoom to bounds if only feature is a bbox

### ISSUE THREAD

**Issue by ebenenglish** [projectblacklight/blacklight-maps#76]
There is an issue with ```setMapBounds()``` in ```blacklight-maps-browse.js``` where the bounds are set to the default (```[[90, 180], [-90, -180]]```) if the only item in the GeoJSON FeatureCollection is a bounding box, rather than setting the bounds to the dimensions of the bbox.

Incorrect bounds for bbox only:
![incorrect bounds for bbox only](https://cdn.pbrd.co/images/13jaoJjK.png)

It should look like this:
![correct bounds for bbox only](https://cdn.pbrd.co/images/13jcRySv.png)

This is because ```markers._featureGroup._layers``` (https://github.com/projectblacklight/blacklight-maps/blob/master/app/assets/javascripts/blacklight-maps/blacklight-maps-browse.js#L185) returns an empty object when the only item is a bounding box (which is definitely a bit surprising), so ```hasAnyFeatures()``` returns false.

Would suggest either:
* (A) modify ```hasAnyFeatures()``` to return true if there is a bounding box object/layer to display, or . . . 

* (B) change ```mapBounds()``` (https://github.com/projectblacklight/blacklight-maps/blob/master/app/assets/javascripts/blacklight-maps/blacklight-maps-browse.js#L162) to return Leaflet's ```markers.getBounds()``` function, which will set the correct bounds if there are markers/bboxes to display (even a single bbox), or if there are no markers, returns a center point or bounds that provides the classic mid-Atlantic-centered map view (see screenshot below).

Default bounds returned by ```getBounds()``` when there are no features:
![default bounds when there are no features](https://cdn.pbrd.co/images/13jfYEeU.png)

B is probably the easier solution, but A could easily be done if we want to preserve the ```[[90, 180], [-90, -180]]``` default bounds feature. Something like this seems to work:
```javascript
/**
* Checks to see if there are any features in the markers MarkerClusterGroup
*/
function hasAnyFeatures() {
  var has_features = false;
  markers.eachLayer(function (layer) {
    if (!$.isEmptyObject(layer)) {
      has_features = true;
    }
  });
  return has_features;
}
```

**Comment by ebenenglish** [comment]
@mejackreed Any thoughts? I can whip up a PR for whichever option is preferable. This is an issue for me in production right now, so the sooner the better. Thanks!

**Comment by mejackreed** [comment]
Option A seems logical, since `hasAnyFeatures` would return bounds if they existed. Right now the method doesn't appear to return bounds if they are there.  It may seem that a combination of the approaches is needed?

**Comment by ebenenglish** [comment]
```hasAnyFeatures``` only returns true or false, and is used by ```markerBounds``` (https://github.com/projectblacklight/blacklight-maps/blob/master/app/assets/javascripts/blacklight-maps/blacklight-maps-browse.js#L173) to determine whether it should invoke the Leaflet ```getBounds``` function, or just return the default bounds (```[[90, 180], [-90, -180]]```).

```hasAnyFeatures``` works just fine for a combination of points, but when the only feature is a bbox, it doesn't work.

I will submit a PR along the lines of solution A above and we can take it from there. Any ideas on how to effectively test that the map is showing the correct bounds?
