### ISSUE TITLE
Is there sample data?

### ISSUE THREAD

**Issue by ismail44** [projectblacklight/blacklight-maps#79]
Is there some sample data that I can import into my dev SOLR instance for development purposes?

**Comment by ebenenglish** [comment]
Yes, there are a handful of sample records available here:

https://github.com/projectblacklight/blacklight-maps/blob/master/spec/fixtures/sample_solr_documents.yml

If you're interested in contributing to the project, please see the [Contributing Guide](https://github.com/projectblacklight/blacklight-maps/blob/master/CONTRIBUTING.md).

**Comment by ismail44** [comment]
Thank you so much for your response. I guess I should have sent a query to
the group as opposed to sending in a Github issue.

Thanks again.
