### ISSUE TITLE
initialview config property not working

### ISSUE THREAD

**Issue by mksndz** [projectblacklight/blacklight-maps#85]
I tried to set the initialview property in my CatalogController:

`config.view.maps.initialview = [[27.741885,-96.987305],[37.874853,-71.279297]]
`

But that didn't take. So I looked around and saw that the data attribute wasn't being set like the other config settings were:

From _index_mapview.html.erb

`
<%= blacklight_map_tag('blacklight-index-map',
                       {data:{searchcontrol: true,
                              catalogpath: search_catalog_path,
                              placenamefield: blacklight_config.view.maps.placename_field,
                              clustercount:'hits',
                              searchresultsview: default_document_index_view_type
                       }}) %>
`

So I added the initalview to the data hash

`<%= blacklight_map_tag('blacklight-index-map',
                       {data:{searchcontrol: true,
                              catalogpath: search_catalog_path,
                              placenamefield: blacklight_config.view.maps.placename_field,
                              clustercount:'hits',
                              searchresultsview: default_document_index_view_type,
                              initialview: blacklight_config.view.maps.initialview
                       }}) %>`

...and changed the config value to a string rather than an array...

`config.view.maps.initialview = '[[27.741885,-96.987305],[37.874853,-71.279297]]'
`

And the config setting now works as expected.

Perhaps I am missing something, but I thought it would be helpful to point this out!

**Comment by ebenenglish** [comment]
Thanks, I noticed this as well just recently, should be fixed soon: https://github.com/projectblacklight/blacklight-maps/pull/83.
